# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Creates new application in InsightAppSec"


class Input:
    APP_DESCRIPTION = "app_description"
    APP_NAME = "app_name"
    

class Output:
    APP_ID = "app_id"
    ERROR_CODE = "error_code"
    MESSAGE = "message"
    STATUS = "status"
    

class CreateAppInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "app_description": {
      "type": "string",
      "title": "Description",
      "description": "Describe application",
      "order": 2
    },
    "app_name": {
      "type": "string",
      "title": "Name",
      "description": "Name of the application",
      "order": 1
    }
  },
  "required": [
    "app_name"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateAppOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "app_id": {
      "type": "string",
      "title": "App ID",
      "description": "Hash value",
      "order": 4
    },
    "error_code": {
      "type": "string",
      "title": "Error code",
      "description": "Error code",
      "order": 3
    },
    "message": {
      "type": "string",
      "title": "Message",
      "description": "Message",
      "order": 2
    },
    "status": {
      "type": "integer",
      "title": "Status",
      "description": "Status code",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
