# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Release a currently held message"


class Input:
    END_DATE = "end_date"
    HASHORMESSAGEID = "hashOrMessageId"
    REASON = "reason"
    SEARCH_BY = "search_by"
    START_DATE = "start_date"
    

class Output:
    DATA = "data"
    

class CreateRemediationIncidentInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "end_date": {
      "type": "string",
      "title": "End Date",
      "description": "The most recent date of messages to remediate. Default value is the end of the current day",
      "order": 5
    },
    "hashOrMessageId": {
      "type": "string",
      "title": "Hash Or Message ID",
      "description": "The file hash or messageId value",
      "order": 2
    },
    "reason": {
      "type": "string",
      "title": "Reason",
      "description": "The reason for creating the remediation incident",
      "order": 1
    },
    "search_by": {
      "type": "string",
      "title": "Search By",
      "description": "The message component in which to search by. When using messageId, the \\"\\u003c\\" \\"\\u003e\\" delimiters are required",
      "default": "hash",
      "enum": [
        "hash",
        "messageId"
      ],
      "order": 3
    },
    "start_date": {
      "type": "string",
      "title": "Start Date",
      "description": "The earliest date of messages to remediate. Default value is one month back",
      "order": 4
    }
  },
  "required": [
    "hashOrMessageId",
    "reason"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateRemediationIncidentOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "data": {
      "$ref": "#/definitions/incident",
      "title": "Data",
      "description": "Incident information",
      "order": 1
    }
  },
  "required": [
    "data"
  ],
  "definitions": {
    "incident": {
      "type": "object",
      "title": "incident",
      "properties": {
        "code": {
          "type": "string",
          "title": "Code",
          "description": "The incident code generated at creation, to be used as a reference for the remediation incident",
          "order": 1
        },
        "create": {
          "type": "string",
          "title": "Create",
          "description": "The incident creation data and time",
          "order": 6
        },
        "failed": {
          "type": "integer",
          "title": "Failed",
          "description": "The number of messages that failed to remediate",
          "order": 9
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "The secure Mimecast remediation ID",
          "order": 5
        },
        "identified": {
          "type": "integer",
          "title": "Identified",
          "description": "The number of messages identified based on the search criteria",
          "order": 7
        },
        "modified": {
          "type": "string",
          "title": "Modified",
          "description": "The date and time of the incident's last change",
          "order": 3
        },
        "reason": {
          "type": "string",
          "title": "Reason",
          "description": "The reason provided at the creation of the remediation incident",
          "order": 4
        },
        "restored": {
          "type": "integer",
          "title": "Restored",
          "description": "The number of messages that were restored from the incident",
          "order": 11
        },
        "searchCriteria": {
          "type": "array",
          "title": "Search Criteria",
          "description": "The search criteria used to identify messages",
          "items": {
            "$ref": "#/definitions/search_criteria"
          },
          "order": 8
        },
        "successful": {
          "type": "integer",
          "title": "Successful",
          "description": "The number successfully remediated messages",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "The type of incident",
          "enum": [
            "manual",
            "automatic",
            "notify_only"
          ],
          "order": 10
        }
      },
      "definitions": {
        "search_criteria": {
          "type": "object",
          "title": "search_criteria",
          "properties": {
            "end": {
              "type": "string",
              "title": "End",
              "description": "The end date of messages included. Default is the current day",
              "order": 1
            },
            "fileHash": {
              "type": "string",
              "title": "Filehash",
              "description": "The file hash used in creation of the remediation incident",
              "order": 2
            },
            "from": {
              "type": "string",
              "title": "From",
              "description": "The sender email address or domain",
              "order": 3
            },
            "messageId": {
              "type": "string",
              "title": "Messageid",
              "description": "The message id use in creation of the remediation incident",
              "order": 4
            },
            "restoreCode": {
              "type": "string",
              "title": "Restore Code",
              "description": "The restore incident code",
              "order": 5
            },
            "start": {
              "type": "string",
              "title": "Start",
              "description": "The start date of messages included",
              "order": 6
            },
            "to": {
              "type": "string",
              "title": "To",
              "description": "The recipient email address or domain",
              "order": 7
            },
            "unremediateCode": {
              "type": "string",
              "title": "Unremediatecode",
              "description": "The Mimecast code used to restore a previously remediated message",
              "order": 8
            }
          }
        }
      }
    },
    "search_criteria": {
      "type": "object",
      "title": "search_criteria",
      "properties": {
        "end": {
          "type": "string",
          "title": "End",
          "description": "The end date of messages included. Default is the current day",
          "order": 1
        },
        "fileHash": {
          "type": "string",
          "title": "Filehash",
          "description": "The file hash used in creation of the remediation incident",
          "order": 2
        },
        "from": {
          "type": "string",
          "title": "From",
          "description": "The sender email address or domain",
          "order": 3
        },
        "messageId": {
          "type": "string",
          "title": "Messageid",
          "description": "The message id use in creation of the remediation incident",
          "order": 4
        },
        "restoreCode": {
          "type": "string",
          "title": "Restore Code",
          "description": "The restore incident code",
          "order": 5
        },
        "start": {
          "type": "string",
          "title": "Start",
          "description": "The start date of messages included",
          "order": 6
        },
        "to": {
          "type": "string",
          "title": "To",
          "description": "The recipient email address or domain",
          "order": 7
        },
        "unremediateCode": {
          "type": "string",
          "title": "Unremediatecode",
          "description": "The Mimecast code used to restore a previously remediated message",
          "order": 8
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
