# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Return message info"


class Input:
    ID = "id"
    

class Output:
    DELIVEREDMESSAGE = "deliveredMessage"
    ID = "id"
    RECIPIENTINFO = "recipientInfo"
    RETENTIONINFO = "retentionInfo"
    STATUS = "status"
    

class GetMessageInfoInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "id": {
      "type": "string",
      "title": "ID",
      "description": "The Mimecast ID of the message to load. This is returned by the message_finder_search action",
      "order": 1
    }
  },
  "required": [
    "id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetMessageInfoOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "deliveredMessage": {
      "type": "object",
      "title": "Delivered Message",
      "description": "If rewriting of this URL in emails is disabled",
      "order": 4
    },
    "id": {
      "type": "string",
      "title": "ID",
      "description": "The Mimecast ID of the message",
      "order": 5
    },
    "recipientInfo": {
      "$ref": "#/definitions/recipientInfo",
      "title": "Recipient Info",
      "description": "An object describing the recipient information applied to the message",
      "order": 3
    },
    "retentionInfo": {
      "$ref": "#/definitions/retentionInfo",
      "title": "Retention Info",
      "description": "An object describing the retention information applied to the message",
      "order": 2
    },
    "status": {
      "type": "string",
      "title": "Status",
      "description": "The message status",
      "order": 1
    }
  },
  "definitions": {
    "components": {
      "type": "object",
      "title": "components",
      "properties": {
        "extension": {
          "type": "string",
          "title": "Extension",
          "description": "Extension",
          "order": 1
        },
        "mimeType": {
          "type": "string",
          "title": "Mimetype",
          "description": "Mimetype",
          "order": 2
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 3
        },
        "size": {
          "type": "integer",
          "title": "Size",
          "description": "Size",
          "order": 4
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Type",
          "order": 5
        }
      }
    },
    "messageInfo": {
      "type": "object",
      "title": "messageInfo",
      "properties": {
        "attachments": {
          "type": "array",
          "title": "Attachments",
          "description": "Attachments",
          "items": {
            "type": "object"
          },
          "order": 1
        },
        "cc": {
          "type": "array",
          "title": "Cc",
          "description": "Cc",
          "items": {
            "type": "string"
          },
          "order": 2
        },
        "fromEnvelope": {
          "type": "string",
          "title": "Fromenvelope",
          "description": "Fromenvelope",
          "order": 3
        },
        "fromHeader": {
          "type": "string",
          "title": "Fromheader",
          "description": "Fromheader",
          "order": 4
        },
        "htmlBody": {
          "type": "string",
          "title": "Htmlbody",
          "description": "Htmlbody",
          "order": 5
        },
        "processed": {
          "type": "string",
          "title": "Processed",
          "description": "Processed",
          "order": 6
        },
        "sent": {
          "type": "string",
          "title": "Sent",
          "description": "Sent",
          "order": 7
        },
        "subject": {
          "type": "string",
          "title": "Subject",
          "description": "Subject",
          "order": 8
        },
        "textBody": {
          "type": "string",
          "title": "Textbody",
          "description": "Textbody",
          "order": 9
        },
        "to": {
          "type": "array",
          "title": "To",
          "description": "To",
          "items": {
            "type": "string"
          },
          "order": 10
        },
        "transmissionInfo": {
          "type": "string",
          "title": "Transmissioninfo",
          "description": "Transmissioninfo",
          "order": 11
        }
      }
    },
    "recipientInfo": {
      "type": "object",
      "title": "recipientInfo",
      "properties": {
        "messageInfo": {
          "$ref": "#/definitions/messageInfo",
          "title": "Message Info",
          "description": "An object describing recipient message information",
          "order": 1
        },
        "recipientMetaInfo": {
          "$ref": "#/definitions/recipientMetaInfo",
          "title": "Recipient Meta Info",
          "description": "An object describing the message meta-data",
          "order": 2
        }
      },
      "definitions": {
        "components": {
          "type": "object",
          "title": "components",
          "properties": {
            "extension": {
              "type": "string",
              "title": "Extension",
              "description": "Extension",
              "order": 1
            },
            "mimeType": {
              "type": "string",
              "title": "Mimetype",
              "description": "Mimetype",
              "order": 2
            },
            "name": {
              "type": "string",
              "title": "Name",
              "description": "Name",
              "order": 3
            },
            "size": {
              "type": "integer",
              "title": "Size",
              "description": "Size",
              "order": 4
            },
            "type": {
              "type": "string",
              "title": "Type",
              "description": "Type",
              "order": 5
            }
          }
        },
        "messageInfo": {
          "type": "object",
          "title": "messageInfo",
          "properties": {
            "attachments": {
              "type": "array",
              "title": "Attachments",
              "description": "Attachments",
              "items": {
                "type": "object"
              },
              "order": 1
            },
            "cc": {
              "type": "array",
              "title": "Cc",
              "description": "Cc",
              "items": {
                "type": "string"
              },
              "order": 2
            },
            "fromEnvelope": {
              "type": "string",
              "title": "Fromenvelope",
              "description": "Fromenvelope",
              "order": 3
            },
            "fromHeader": {
              "type": "string",
              "title": "Fromheader",
              "description": "Fromheader",
              "order": 4
            },
            "htmlBody": {
              "type": "string",
              "title": "Htmlbody",
              "description": "Htmlbody",
              "order": 5
            },
            "processed": {
              "type": "string",
              "title": "Processed",
              "description": "Processed",
              "order": 6
            },
            "sent": {
              "type": "string",
              "title": "Sent",
              "description": "Sent",
              "order": 7
            },
            "subject": {
              "type": "string",
              "title": "Subject",
              "description": "Subject",
              "order": 8
            },
            "textBody": {
              "type": "string",
              "title": "Textbody",
              "description": "Textbody",
              "order": 9
            },
            "to": {
              "type": "array",
              "title": "To",
              "description": "To",
              "items": {
                "type": "string"
              },
              "order": 10
            },
            "transmissionInfo": {
              "type": "string",
              "title": "Transmissioninfo",
              "description": "Transmissioninfo",
              "order": 11
            }
          }
        },
        "recipientMetaInfo": {
          "type": "object",
          "title": "recipientMetaInfo",
          "properties": {
            "binaryEmailSize": {
              "type": "integer",
              "title": "Binaryemailsize",
              "description": "Binaryemailsize",
              "order": 1
            },
            "components": {
              "type": "array",
              "title": "Components",
              "description": "Components",
              "items": {
                "$ref": "#/definitions/components"
              },
              "order": 2
            },
            "encryptionInfo": {
              "type": "string",
              "title": "Encryptioninfo",
              "description": "Encryptioninfo",
              "order": 3
            },
            "messageExpiresIn": {
              "type": "integer",
              "title": "Messageexpiresin",
              "description": "Messageexpiresin",
              "order": 4
            },
            "processingServer": {
              "type": "string",
              "title": "Processingserver",
              "description": "Processingserver",
              "order": 5
            },
            "receiptAcknowledgement": {
              "type": "string",
              "title": "Receiptacknowledgement",
              "description": "Receiptacknowledgement",
              "order": 6
            },
            "receiptEvent": {
              "type": "string",
              "title": "Receiptevent",
              "description": "Receiptevent",
              "order": 7
            },
            "remoteHost": {
              "type": "string",
              "title": "Remotehost",
              "description": "Remotehost",
              "order": 8
            },
            "remoteIp": {
              "type": "string",
              "title": "Remoteip",
              "description": "Remoteip",
              "order": 9
            },
            "remoteServerGreeting": {
              "type": "string",
              "title": "Remoteservergreeting",
              "description": "Remoteservergreeting",
              "order": 10
            },
            "spamEvent": {
              "type": "string",
              "title": "Spamevent",
              "description": "Spamevent",
              "order": 11
            },
            "transmissionEnd": {
              "type": "string",
              "title": "Transmissionend",
              "description": "Transmissionend",
              "order": 12
            },
            "transmissionSize": {
              "type": "integer",
              "title": "Transmissionsize",
              "description": "Transmissionsize",
              "order": 13
            },
            "transmissionStart": {
              "type": "string",
              "title": "Transmissionstart",
              "description": "Transmissionstart",
              "order": 14
            }
          },
          "definitions": {
            "components": {
              "type": "object",
              "title": "components",
              "properties": {
                "extension": {
                  "type": "string",
                  "title": "Extension",
                  "description": "Extension",
                  "order": 1
                },
                "mimeType": {
                  "type": "string",
                  "title": "Mimetype",
                  "description": "Mimetype",
                  "order": 2
                },
                "name": {
                  "type": "string",
                  "title": "Name",
                  "description": "Name",
                  "order": 3
                },
                "size": {
                  "type": "integer",
                  "title": "Size",
                  "description": "Size",
                  "order": 4
                },
                "type": {
                  "type": "string",
                  "title": "Type",
                  "description": "Type",
                  "order": 5
                }
              }
            }
          }
        }
      }
    },
    "recipientMetaInfo": {
      "type": "object",
      "title": "recipientMetaInfo",
      "properties": {
        "binaryEmailSize": {
          "type": "integer",
          "title": "Binaryemailsize",
          "description": "Binaryemailsize",
          "order": 1
        },
        "components": {
          "type": "array",
          "title": "Components",
          "description": "Components",
          "items": {
            "$ref": "#/definitions/components"
          },
          "order": 2
        },
        "encryptionInfo": {
          "type": "string",
          "title": "Encryptioninfo",
          "description": "Encryptioninfo",
          "order": 3
        },
        "messageExpiresIn": {
          "type": "integer",
          "title": "Messageexpiresin",
          "description": "Messageexpiresin",
          "order": 4
        },
        "processingServer": {
          "type": "string",
          "title": "Processingserver",
          "description": "Processingserver",
          "order": 5
        },
        "receiptAcknowledgement": {
          "type": "string",
          "title": "Receiptacknowledgement",
          "description": "Receiptacknowledgement",
          "order": 6
        },
        "receiptEvent": {
          "type": "string",
          "title": "Receiptevent",
          "description": "Receiptevent",
          "order": 7
        },
        "remoteHost": {
          "type": "string",
          "title": "Remotehost",
          "description": "Remotehost",
          "order": 8
        },
        "remoteIp": {
          "type": "string",
          "title": "Remoteip",
          "description": "Remoteip",
          "order": 9
        },
        "remoteServerGreeting": {
          "type": "string",
          "title": "Remoteservergreeting",
          "description": "Remoteservergreeting",
          "order": 10
        },
        "spamEvent": {
          "type": "string",
          "title": "Spamevent",
          "description": "Spamevent",
          "order": 11
        },
        "transmissionEnd": {
          "type": "string",
          "title": "Transmissionend",
          "description": "Transmissionend",
          "order": 12
        },
        "transmissionSize": {
          "type": "integer",
          "title": "Transmissionsize",
          "description": "Transmissionsize",
          "order": 13
        },
        "transmissionStart": {
          "type": "string",
          "title": "Transmissionstart",
          "description": "Transmissionstart",
          "order": 14
        }
      },
      "definitions": {
        "components": {
          "type": "object",
          "title": "components",
          "properties": {
            "extension": {
              "type": "string",
              "title": "Extension",
              "description": "Extension",
              "order": 1
            },
            "mimeType": {
              "type": "string",
              "title": "Mimetype",
              "description": "Mimetype",
              "order": 2
            },
            "name": {
              "type": "string",
              "title": "Name",
              "description": "Name",
              "order": 3
            },
            "size": {
              "type": "integer",
              "title": "Size",
              "description": "Size",
              "order": 4
            },
            "type": {
              "type": "string",
              "title": "Type",
              "description": "Type",
              "order": 5
            }
          }
        }
      }
    },
    "retentionInfo": {
      "type": "object",
      "title": "retentionInfo",
      "properties": {
        "audits": {
          "type": "array",
          "title": "Audits",
          "description": "An array of objects describing the date, type, and information about any audits carried out on the message",
          "items": {
            "type": "object"
          },
          "order": 1
        },
        "currentPurgeDate": {
          "type": "string",
          "title": "Current Purge Date",
          "description": "The date that the message is scheduled to be purged from Mimecast",
          "order": 2
        },
        "fbrExpireCheck": {
          "type": "array",
          "title": "FBR Expire Check",
          "description": "An array of date strings describing when Granular Retention policies were checked, if applicable",
          "items": {
            "type": "object"
          },
          "order": 3
        },
        "fbrStamps": {
          "type": "array",
          "title": "FBR Stamps",
          "description": "An array of objects describing the email address, folder, recipient visibility, expiry, purge, and policy fields applied to the message as a result of a Granular retention policy action, if applicable",
          "items": {
            "type": "object"
          },
          "order": 4
        },
        "litigationHoldInfo": {
          "type": "array",
          "title": "Litigation Hold Info",
          "description": "An array containing objects describing the expiry, description and Mimecast ID of any litigation hold policies applied to the message",
          "items": {
            "type": "object"
          },
          "order": 5
        },
        "originalPurgeDate": {
          "type": "string",
          "title": "Original Purge Date",
          "description": "The message's original purge date",
          "order": 6
        },
        "purgeBasedOn": {
          "type": "string",
          "title": "Purge Based On",
          "description": "Describes what the message purge date is based on",
          "order": 7
        },
        "retentionAdjustmentDays": {
          "type": "integer",
          "title": "Retention Adjustment Days",
          "description": "The number of days that a retention adjustment has been applied to the message",
          "order": 8
        },
        "smartTags": {
          "type": "array",
          "title": "Smart Tags",
          "description": "An array of smart tag objects that the message is assigned to",
          "items": {
            "type": "object"
          },
          "order": 9
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
