# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Get counts of currenlty held messages for each hold reason"


class Input:
    pass

class Output:
    NUMBER_OF_ITEMS = "number_of_items"
    POLICY_INFO = "policy_info"
    

class GetMessageHoldSummaryListInput(komand.Input):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetMessageHoldSummaryListOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "number_of_items": {
      "type": "integer",
      "title": "Number Of Items",
      "description": "The number of messages currenlty held for this reason",
      "order": 2
    },
    "policy_info": {
      "type": "string",
      "title": "Policy Info",
      "description": "The name of the policy or definition that held a message",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
