# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Download logs given a query and timeframe"


class Input:
    FROM_MILLIS = "from_millis"
    LIMIT = "limit"
    LOGS = "logs"
    QUERY = "query"
    TO_MILLIS = "to_millis"
    

class Output:
    DOWNLOADED_LOGS = "downloaded_logs"
    

class DownloadLogsInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "from_millis": {
      "type": "string",
      "title": "From",
      "description": "Timeframe start in epoch millis",
      "order": 3
    },
    "limit": {
      "type": "string",
      "title": "Limit",
      "description": "Max number of files to download",
      "order": 5
    },
    "logs": {
      "type": "array",
      "title": "log IDs",
      "description": "Array of logs to search",
      "items": {
        "type": "string"
      },
      "order": 2
    },
    "query": {
      "type": "string",
      "title": "Query",
      "description": "Advanced leql query",
      "order": 1
    },
    "to_millis": {
      "type": "string",
      "title": "To",
      "description": "Timeframe end in epoch millis",
      "order": 4
    }
  },
  "required": [
    "from_millis",
    "logs",
    "to_millis"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DownloadLogsOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "downloaded_logs": {
      "type": "array",
      "title": "Downloaded Logs",
      "description": "Logs downloaded that match the supplied query",
      "items": {
        "type": "object"
      },
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
