# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="paloalto_wildfire-miketest-plugin",
      version="1.1.2",
      description="Perform malware analysis with Palo Alto Wildfire",
      author="miketest",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_paloalto_wildfire']
      )
