# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Store page contents"


class Input:
    CONTENTS = "contents"
    PAGE = "page"
    SPACE = "space"
    

class Output:
    PAGE = "page"
    

class StorePageContentInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "contents": {
      "type": "string",
      "title": "Contents",
      "description": "Contents to store",
      "order": 3
    },
    "page": {
      "type": "string",
      "title": "Page Name",
      "description": "Page name",
      "order": 1
    },
    "space": {
      "type": "string",
      "title": "Space",
      "description": "Space",
      "order": 2
    }
  },
  "required": [
    "contents",
    "page",
    "space"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class StorePageContentOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "page": {
      "$ref": "#/definitions/page",
      "title": "Page",
      "description": "Page stored",
      "order": 1
    }
  },
  "definitions": {
    "page": {
      "type": "object",
      "title": "page",
      "properties": {
        "content": {
          "type": "string",
          "title": "Page Contents",
          "description": "Page contents",
          "order": 5
        },
        "contentStatus": {
          "type": "string",
          "title": "Content Status",
          "description": "Content status",
          "order": 14
        },
        "created": {
          "type": "string",
          "title": "Created Date",
          "displayType": "date",
          "description": "Created date",
          "format": "date-time",
          "order": 4
        },
        "creator": {
          "type": "string",
          "title": "Creator",
          "description": "Creator user",
          "order": 8
        },
        "current": {
          "type": "boolean",
          "title": "Current",
          "description": "True if current version",
          "order": 13
        },
        "homePage": {
          "type": "boolean",
          "title": "Home Page",
          "description": "Home page",
          "order": 11
        },
        "id": {
          "type": "string",
          "title": "Page ID",
          "description": "Page ID",
          "order": 12
        },
        "modified": {
          "type": "string",
          "title": "Modified Date",
          "displayType": "date",
          "description": "Modified date",
          "format": "date-time",
          "order": 15
        },
        "modifier": {
          "type": "string",
          "title": "Modifier User",
          "description": "Modifier user",
          "order": 3
        },
        "parentId": {
          "type": "string",
          "title": "Parent Page ID",
          "description": "Parent page ID",
          "order": 9
        },
        "permissions": {
          "type": "string",
          "title": "Permissions",
          "description": "Permissions",
          "order": 7
        },
        "space": {
          "type": "string",
          "title": "Space",
          "description": "Space",
          "order": 2
        },
        "title": {
          "type": "string",
          "title": "Page Title",
          "description": "Page title",
          "order": 1
        },
        "url": {
          "type": "string",
          "title": "URL",
          "description": "URL",
          "order": 6
        },
        "version": {
          "type": "string",
          "title": "Version",
          "description": "Page version",
          "order": 10
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
