# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Get information about an exisiting incident"


class Input:
    ID = "id"
    

class Output:
    DATA = "data"
    

class GetRemediationIncidentInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "id": {
      "type": "string",
      "title": "ID",
      "description": "The Mimecast ID for a remediation incident, provided when an incident is created",
      "order": 1
    }
  },
  "required": [
    "id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetRemediationIncidentOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "data": {
      "$ref": "#/definitions/incident",
      "title": "Data",
      "description": "Incident information",
      "order": 1
    }
  },
  "required": [
    "data"
  ],
  "definitions": {
    "incident": {
      "type": "object",
      "title": "incident",
      "properties": {
        "code": {
          "type": "string",
          "title": "Code",
          "description": "The incident code generated at creation, to be used as a reference for the remediation incident",
          "order": 1
        },
        "create": {
          "type": "string",
          "title": "Create",
          "description": "The incident creation data and time",
          "order": 6
        },
        "failed": {
          "type": "integer",
          "title": "Failed",
          "description": "The number of messages that failed to remediate",
          "order": 9
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "The secure Mimecast remediation ID",
          "order": 5
        },
        "identified": {
          "type": "integer",
          "title": "Identified",
          "description": "The number of messages identified based on the search criteria",
          "order": 7
        },
        "modified": {
          "type": "string",
          "title": "Modified",
          "description": "The date and time of the incident's last change",
          "order": 3
        },
        "reason": {
          "type": "string",
          "title": "Reason",
          "description": "The reason provided at the creation of the remediation incident",
          "order": 4
        },
        "restored": {
          "type": "integer",
          "title": "Restored",
          "description": "The number of messages that were restored from the incident",
          "order": 11
        },
        "searchCriteria": {
          "type": "array",
          "title": "Search Criteria",
          "description": "The search criteria used to identify messages",
          "items": {
            "$ref": "#/definitions/search_criteria"
          },
          "order": 8
        },
        "successful": {
          "type": "integer",
          "title": "Successful",
          "description": "The number successfully remediated messages",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "The type of incident",
          "enum": [
            "manual",
            "automatic",
            "notify_only"
          ],
          "order": 10
        }
      },
      "definitions": {
        "search_criteria": {
          "type": "object",
          "title": "search_criteria",
          "properties": {
            "end": {
              "type": "string",
              "title": "End",
              "description": "The end date of messages included. Default is the current day",
              "order": 1
            },
            "fileHash": {
              "type": "string",
              "title": "Filehash",
              "description": "The file hash used in creation of the remediation incident",
              "order": 2
            },
            "from": {
              "type": "string",
              "title": "From",
              "description": "The sender email address or domain",
              "order": 3
            },
            "messageId": {
              "type": "string",
              "title": "Messageid",
              "description": "The message id use in creation of the remediation incident",
              "order": 4
            },
            "restoreCode": {
              "type": "string",
              "title": "Restore Code",
              "description": "The restore incident code",
              "order": 5
            },
            "start": {
              "type": "string",
              "title": "Start",
              "description": "The start date of messages included",
              "order": 6
            },
            "to": {
              "type": "string",
              "title": "To",
              "description": "The recipient email address or domain",
              "order": 7
            },
            "unremediateCode": {
              "type": "string",
              "title": "Unremediatecode",
              "description": "The Mimecast code used to restore a previously remediated message",
              "order": 8
            }
          }
        }
      }
    },
    "search_criteria": {
      "type": "object",
      "title": "search_criteria",
      "properties": {
        "end": {
          "type": "string",
          "title": "End",
          "description": "The end date of messages included. Default is the current day",
          "order": 1
        },
        "fileHash": {
          "type": "string",
          "title": "Filehash",
          "description": "The file hash used in creation of the remediation incident",
          "order": 2
        },
        "from": {
          "type": "string",
          "title": "From",
          "description": "The sender email address or domain",
          "order": 3
        },
        "messageId": {
          "type": "string",
          "title": "Messageid",
          "description": "The message id use in creation of the remediation incident",
          "order": 4
        },
        "restoreCode": {
          "type": "string",
          "title": "Restore Code",
          "description": "The restore incident code",
          "order": 5
        },
        "start": {
          "type": "string",
          "title": "Start",
          "description": "The start date of messages included",
          "order": 6
        },
        "to": {
          "type": "string",
          "title": "To",
          "description": "The recipient email address or domain",
          "order": 7
        },
        "unremediateCode": {
          "type": "string",
          "title": "Unremediatecode",
          "description": "The Mimecast code used to restore a previously remediated message",
          "order": 8
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
